name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - '2.6'
        gemfile:
        # - 'gemfiles/rails_4.gemfile'
        - 'gemfiles/rails_5.gemfile'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: '1'
        bundler-cache: true
    - name: Install dependencies
      run: |
        BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install
    - name: Run tests
      run: |
        BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec rake
